#!/bin/bash

export INSTALL_DIR=$(<.path)

export PROTOCOL="tcp"

export PORT="1194"

export DNS_SERVER_1="8.8.8.8"

export DNS_SERVER_2="8.8.4.4"

export PUBLIC_IP="$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)"

# Anything after this line was generated by scripts